### ISSUE TITLE
Deprecated WETH on Add Liquidity

### ISSUE THREAD

**Issue by IvanRF** [fuseio/fuseswap-service#35]
https://github.com/fuseio/fuseswap-service/blob/af6bf909a59cd2dca771fcf305fc9a51603fd97b/src/constants/index.ts#L35

The `Common bases` section of Add Liquidity (shown when you click on `Select a token`) still points to the old WETH contract.

`WETH (Deprecated)` is not listed in the `FuseSwap Token List` but can be selected from `Common bases`.

**Comment by leonprou** [comment]
Thanks for noticing and opening an issue.
Can you explaon more about the common bases? Maybe adding a screenshot. If it's in the fuseswap UI I think it's not related to this.
@mul53 can you check out where's `WETH_ADDRESS` is used?

**Comment by mul53** [comment]
@leonprou i will create an update in fuseswap-interface and this repo, so it means orders are been routed through the deprecated weth

**Comment by IvanRF** [comment]
> If it's in the fuseswap UI I think it's not related to this.

@leonprou Yes, the issue is on the UI but the `fuseswap-interface` repository has the Issues section of GitHub disabled.
Could you enable the Issues on GitHub for the UI?

Looking at @mul53 PRs, these were the correct places for the issue 😃 :

https://github.com/fuseio/fuseswap-interface/blob/f0c70ffca7722bad72bcfd0c1e34e5885e50cdb3/src/constants/index.ts#L94

https://github.com/fuseio/fuseswap-interface/blob/f0c70ffca7722bad72bcfd0c1e34e5885e50cdb3/src/constants/index.ts#L139

**Comment by leonprou** [comment]
> > If it's in the fuseswap UI I think it's not related to this.
> 
> @leonprou Yes, the issue is on the UI but the `fuseswap-interface` repository has the Issues section of GitHub disabled.
> Could you enable the Issues on GitHub for the UI?
> 
> Looking at @mul53 PRs, these were the correct places for the issue 😃 :
> 
> https://github.com/fuseio/fuseswap-interface/blob/f0c70ffca7722bad72bcfd0c1e34e5885e50cdb3/src/constants/index.ts#L94
> 
> https://github.com/fuseio/fuseswap-interface/blob/f0c70ffca7722bad72bcfd0c1e34e5885e50cdb3/src/constants/index.ts#L139

cool. thanks for the pointers 👍 
just opened issues on the https://github.com/fuseio/fuseswap-interface/issues

**Comment by IvanRF** [comment]
I can see in the UI now that this issue was solved 👍
